language: cpp
compiler:
    - clang
    - gcc
os:
    - linux
branches:
    only:
        - master
# Use container-based Ubuntu 14.04 infrastructure.
sudo: false
dist: trusty
addons:
    apt:
        packages:
            - cmake
            - graphviz
            - libboost1.60-all-dev
notifications:
    email: false
script:
    - mkdir build
    - cd build
    - cmake ..
    - make
