language: cpp
compiler:
    - gcc
os:
    - linux
branches:
    only:
        - master
# Use container-based Ubuntu 14.04 infrastructure.
sudo: false
dist: trusty
addons:
    apt:
        sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
        packages:
            - cmake
            - g++-7
            - graphviz
            - libboost-all-dev
notifications:
    email: false
script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=/usr/bin/g++-7 ..
    - make
